### ISSUE TITLE
Top bar tagline overlapping first menu item

### ISSUE THREAD

**Issue by alysbrett** [UKRSE/UKRSE.github.io#41]
In both Firefox and Chrome, the new RSE Conference 2016 menu item is almost entirely overlapping the end of "The UK Community of Research Software Engineers" at the default text size. Looks good if I zoom out to 90%

**Comment by hainesr** [comment]
What resolution are you using (width)?

I suspect this is just running out of room...

**Comment by hainesr** [comment]
Aha, it seems that @SimonHettrick fixed this. Thanks!
